using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using RuntimeInvestigation.Application.Features.Templates;
using RuntimeInvestigation.Domain.Entities;

namespace RuntimeInvestigation.Infrastructure.Persistence;

public static class TemplateSeeder
{
    public static IReadOnlyList<InvestigationTemplate> GetDefaultTemplates()
    {
        return new List<InvestigationTemplate>
        {
            new(
                name: "Debug N+1 Queries",
                description: "Investigate excessive database queries and repeated roundtrips generated by ORM operations.",
                category: "Performance",
                probes: new List<ProbeTemplate>
                {
                    new(ProbeType.Log, "Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler", "Execute", Expression: "queryExpression", DurationMinutes: 30),
                    new(ProbeType.Metric, "System.Data.Common.DbCommand", "ExecuteReader", Expression: "CommandText", DurationMinutes: 30),
                    new(ProbeType.Log, "System.Data.Common.DbCommand", "ExecuteNonQuery", Expression: "CommandText", DurationMinutes: 30)
                }
            ),
            new(
                name: "Authentication Failures",
                description: "Capture authentication and authorization rejection patterns across security boundaries.",
                category: "Security",
                probes: new List<ProbeTemplate>
                {
                    new(ProbeType.Log, "Microsoft.AspNetCore.Authentication.AuthenticationService", "AuthenticateAsync", Expression: "scheme", Condition: "result == false", DurationMinutes: 60),
                    new(ProbeType.Metric, "RuntimeInvestigation.API.Controllers.AuthController", "Login", Expression: "model.Email", DurationMinutes: 60)
                }
            ),
            new(
                name: "Memory Leak",
                description: "Capture heap snapshots and allocation tracking on heavy memory routines.",
                category: "Diagnostics",
                probes: new List<ProbeTemplate>
                {
                    new(ProbeType.Snapshot, "System.GC", "Collect", Expression: "generation", DurationMinutes: 45),
                    new(ProbeType.Metric, "System.Runtime.CompilerServices.RuntimeHelpers", "AllocateUninitializedArray", Expression: "length", Condition: "length > 100000", DurationMinutes: 45)
                }
            )
        };
    }

    public static async Task SeedAsync(ITemplateRepository repository, CancellationToken cancellationToken = default)
    {
        var existing = await repository.GetAllAsync(cancellationToken);
        if (existing.Count > 0)
        {
            return;
        }

        foreach (var template in GetDefaultTemplates())
        {
            await repository.CreateAsync(template, cancellationToken);
        }
    }
}
